Organizations:
    - &Org5            
        Name: Org5MSP
        ID: Org5MSP
        MSPDir: crypto-config/peerOrganizations/org5.jnvr.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org5MSP.admin', 'Org5MSP.peer', 'Org5MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org5MSP.admin', 'Org5MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org5MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org5MSP.peer')"
        AnchorPeers:
            - Host: peer0.org5.jnvr.com
              Port: 7051
