    ################################################################################
    #   crypto-config.yaml
    ################################################################################
    OrdererOrgs:
    - Name: Orderer
      Domain: jnvr.com
      EnableNodeOUs: true
      Specs:
        - Hostname: orderer
          SANS:
            - localhost
    PeerOrgs:
    - Name: Org1
      Domain: org1.jnvr.com
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Org2
      Domain: org2.jnvr.com
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Org3
      Domain: org3.jnvr.com
      EnableNodeOUs: true    
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Org4
      Domain: org4.jnvr.com
      EnableNodeOUs: true    
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
